apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
spec:
  selector:
    app: elasticsearch
  # Set up a headless service
  clusterIP: None
  ports:
    # The HTTP API interface for client requests
  - name: http-api
    port: 9200
    targetPort: 9200
    # The transport interface for inter-node communication
  - name: inter-node
    port: 9300
    targetPort: 9300
